config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#root'

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:create, :update, :show]
    get '/profile', to: 'users#profile'
    resource :session, only: [:create, :destroy]

    resources :categories, only: [:index, :create]
    resources :comments, only: [:create, :destroy]

    resources :suggestions, except: [:new, :edit] do
      patch "/pending_upvote", to: "suggestions#pending_upvote", as: "pending_upvote"
      patch "/ignore_upvote", to: "suggestions#ignore_upvote", as: "ignore_upvote"
      patch "/complete_upvote", to: "suggestions#complete_upvote", as: "complete_upvote"
    end

    resources :events, except: [:new, :edit] do
      patch "/pending_upvote", to: "events#pending_upvote", as: "pending_upvote"
      patch "/ignore_upvote", to: "events#ignore_upvote", as: "ignore_upvote"
      patch "/complete_upvote", to: "events#complete_upvote", as: "complete_upvote"
    end

    resources :contacts, only: [:create, :index]

    # get "/about", to: "static_pages#about", as: "about"
    # get "/contact", to: "contacts#new", as: "contact"
    #
    # get '/near_me', to: "events#near_me", as: "events_near_me"
    # get 'hot_events', to: "events#most_upvoted", as: "events_most_upvoted"
    # get 'trending_events', to: "events#trending", as: "events_trending"
    #
    # get 'hot_suggestions', to: "suggestions#most_upvoted", as: "suggestions_most_upvoted"
    # get 'trending_suggestions', to: "suggestions#trending", as: "suggestions_trending"
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  username        :string           not null
#  password_digest :string           not null
#  admin           :boolean          default("false"), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  session_token   :string           not null
#  zip_code        :integer
#

class User < ActiveRecord::Base
  has_secure_password

  validates :email, :password_digest, :session_token, presence: true
  validates :username, presence: true, uniqueness: true, length: { maximum: 25 }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates_format_of :zip_code, :with => /\A\d{5}\z/, :message => "should be in the form 12345", allow_nil: true
  validates :zip_code, numericality: { only_integer: true }, allow_nil: true
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :suggestions,
    class_name: "Suggestion",
    primary_key: :id,
    foreign_key: :creator_id,
    dependent: :destroy

  has_many :events,
    class_name: "Event",
    primary_key: :id,
    foreign_key: :creator_id,
    dependent: :destroy

  has_many :comments

  has_many :upvotes, dependent: :destroy
  has_many :supported_suggestions, through: :upvotes, source: :idea, source_type: "Suggestion"
  has_many :supported_events, through: :upvotes, source: :idea, source_type: "Event"

  def self.generate_random_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = self.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end

  # def password=(password)
  #   @password = password
  #   self.password_digest = BCrypt::Password.create(password)
  # end

  def upvoted_idea_ids
    @upvoted_idea_ids ||= upvotes.pluck(:idea_id)
  end

  def upvoted?(idea)
    upvoted_idea_ids.include?(idea.id)
  end

  def is_password?(password)
    # BCrypt::Password.new(password_digest).is_password?(password)
    !!self.try(:authenticate, password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_random_token
    self.save
    self.session_token
  end

  def formatted_location
    "Laura fix this!"
    # if city != "" && state
    #   "#{city}, #{state}"
    # elsif state
    #   state
    # elsif city
    #   city
    # else
    #   "Not set"
    # end
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_random_token
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :must_log_in_to_see_profile, only: [:profile]

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      render partial: 'user', locals: { user: @user }
    else
      render json: @user.errors.full_messages, status: 422
    end
  end
  #
  def show
    @upvotes = Upvote.where(user_id: params[:id]).includes(idea: [:categories, :creator, :upvotes])
    @user = User.find(params[:id])
    render :show
  end

  def profile
    if params[:actions]
      if params[:actions] == "mine"
        @upvotes = Upvote.includes(suggestion: [:categories, :creator, :upvotes])
        .where(user_id: current_user.id)
        .where(status: "complete")
        .where(suggestions: { creator: current_user } )
      elsif params[:actions] == "completed"
        @upvotes = Upvote.includes(suggestion: [:categories, :creator, :upvotes])
        .where(user_id: current_user.id)
        .where(status: "complete")
        .where.not(suggestions: { creator: current_user } )
      else
        @upvotes = Upvote.where(user_id: current_user.id)
        .where(idea_type: "Suggestion")
        .where(status: "pending")
        .includes(idea: [:categories, :creator, :upvotes])
      end
    else
      if params[:events] == "mine"
        @upvotes = Upvote.includes(event: [:categories, :creator, :upvotes])
        .where(user_id: current_user.id)
        .where(status: "complete")
        .where(events: { creator: current_user } )
      elsif params[:events] == "completed"
        @upvotes = Upvote.includes(event: [:categories, :creator, :upvotes])
        .where(user_id: current_user.id)
        .where.not(events: { creator: current_user } )
        .where.not(status: "ignore")
        .where("events.date < ?", Date.today)
      else
        @upvotes = Upvote.includes(event: [:categories, :creator, :upvotes])
        .where(user_id: current_user.id)
        .where.not(events: { creator: current_user } )
        .where.not(status: "ignore")
        .where("events.date > ?", Date.today)
      end
    end

    @user = current_user
    render :profile
  end
  #
  # def edit
  #   @user = User.find(params[:id])
  #   render :edit
  # end
  #
  # def update
  #   @user = User.find(params[:id])
  #
  #   if @user.update(user_params)
  #     redirect_to user_url(@user)
  #   else
  #     flash.now[:errors] = @user.errors.full_messages
  #     render :edit
  #   end
  # end
  #
  private

  def must_log_in_to_see_profile
    unless logged_in?
      render json: ["Please log in to see your profile"], status: 403
    end
  end
end

app/views/users/_form.html.erb
<% action_url = action_type == :new ? users_url : user_url(user) %>
<% message = action_type == :new ? "Sign Up" : "Edit Information" %>

<form action="<%= action_url %>" method="post">
  <fieldset>
    <%= form_auth_token %>
    <legend><%= legend %></legend>

    <% if action_type == :edit %>
      <input type="hidden" name="_method" value="patch">
    <% end %>

    <label for="user_username">Username</label>
    <input id="user_username" type="text" name="user[username]" value="<%= user.username %>" placeholder="choose a username">

    <label for="user_password">Password</label>
    <input id="user_password" type="password" name="user[password]" placeholder="password">

    <label for="uesr_password_confirmation">Password Confirmation</label>
    <input id="uesr_password_confirmation" type="password" name="user[password_confirmation]" placeholder="confirm password">

    <label for="user_email">E-mail</label>
    <input id="user_email" type="text" name="user[email]" value="<%= user.email %>" placeholder="e-mail (never shown)">

    <label for="user_city">Zip Code</label>
    <input id="user_zip_code" type="text" name="user[zip_code]" value="<%= user.zip_code %>" placeholder="zip code (optional)">

    <button type="submit"><%= message %></button>
  </fieldset>
</form>

app/views/users/_location.html.erb
<form class="" action="<%= user_url(user) %>" method="post">
  <%= form_auth_token %>
  <input type="hidden" name="_method" value="patch">

  <label for="user_city">City</label>
  <input type="text" name="user[city]" value="<%= user.city %>" placeholder="city (optional)">

  <label for="user_state" class="col-lg-2 control-label">State</label>
  <select name="user[state]" id="user_state">
    <option disabled selected>Select State</option>
    <% us_states.each do |state| %>
      <option value="<%= state[0] %>"
        <%= "selected" if user.state == state[0] %>><%= state[0] %></option>
    <% end %>
  </select>

  <button type="submit">Edit Location</button>
</form>

app/views/users/edit.html.erb
<h1>Edit Location</h1>

<%= render "location", user: @user %>

app/views/users/index.html.erb
<h1>All the users!</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.username %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<p>Already a member? <%= link_to "Sign In", new_session_url %></p>

<%= render "form", action_type: :new, user: @user, legend: "Sign Up" %>

app/views/users/show.html.erb
<h3>Location: <%= @user.formatted_location %></h3>
<p><%= link_to "Edit Location", edit_user_url(@user) %></p>
<p><a href="#my_events">Down to my created events</p>
<p><a href="#supported_actions">Down to actions I support</p>
<p><a href="#supported_events">Down to events I support</p>

<h3>My Created Actions</h3>
<% if @user.suggestions.empty? %>
  <p>You haven't created any actions yet! <%= link_to "Get started now!", new_suggestion_url %></p>
<% else %>
  <%= render partial: "layouts/short_idea", locals: { ideas: @user.suggestions, idea_type: :suggestion } %>
<% end %>


<h3 id="my_events">My Created Events</h3>
<% if @user.events.empty? %>
  <p>You haven't created any events yet! <%= link_to "Get started now!", new_event_url %></p>
<% else %>
  <%= render partial: "layouts/short_idea", locals: { ideas: @user.events, idea_type: :event } %>
<% end %>

<h3 id="supported_actions">Actions That I Support</h3>
<% if @user.supported_suggestions.empty? %>
  <p>You haven't supported any actions yet! <%= link_to "Check some out now!", root_url %></p>
<% else %>
  <%= render partial: "layouts/short_idea", locals: { ideas: @user.supported_suggestions, idea_type: :suggestion } %>
<% end %>

<h3 id="supported_events">Events That I Support</h3>
<% if @user.supported_events.empty? %>
  <p>You haven't signed up for any events yet! <%= link_to "Check some out now!", events_url %></p>
<% else %>
  <%= render partial: "layouts/short_idea", locals: { ideas: @user.supported_events, idea_type: :event } %>
<% end %>