config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#root'

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:create, :update, :show]
    get '/profile', to: 'users#profile'
    resource :session, only: [:create, :destroy]

    resources :categories, only: [:index, :create]
    resources :comments, only: [:create, :destroy]

    resources :suggestions, except: [:new, :edit] do
      patch "/pending_upvote", to: "suggestions#pending_upvote", as: "pending_upvote"
      patch "/ignore_upvote", to: "suggestions#ignore_upvote", as: "ignore_upvote"
      patch "/complete_upvote", to: "suggestions#complete_upvote", as: "complete_upvote"
    end

    resources :events, except: [:new, :edit] do
      patch "/pending_upvote", to: "events#pending_upvote", as: "pending_upvote"
      patch "/ignore_upvote", to: "events#ignore_upvote", as: "ignore_upvote"
      patch "/complete_upvote", to: "events#complete_upvote", as: "complete_upvote"
    end

    resources :contacts, only: [:create, :index]

    # get "/about", to: "static_pages#about", as: "about"
    # get "/contact", to: "contacts#new", as: "contact"
    #
    # get '/near_me', to: "events#near_me", as: "events_near_me"
    # get 'hot_events', to: "events#most_upvoted", as: "events_most_upvoted"
    # get 'trending_events', to: "events#trending", as: "events_trending"
    #
    # get 'hot_suggestions', to: "suggestions#most_upvoted", as: "suggestions_most_upvoted"
    # get 'trending_suggestions', to: "suggestions#trending", as: "suggestions_trending"
  end
end

app/views/shared/_nav.html.erb
  <nav class="main-nav">
  <div class="logo">
    <a href="<%= root_url %>" class="logo">
    <%= image_tag "angry_cat.png" %>
    F*** That Noise</a>
  </div>

  <ul class="nav-items">
    <% if logged_in? %>
    <li>
      <a href="#"><%= current_user.username %></a>
      <ul class="dropdown-nav hidden">
        <li><a href="<%= user_url(current_user) %>">Profile</a></li>
        <li><%= button_to "Sign Out", session_url, method: :delete %></li>
      </ul>
    </li>
    <% else %>
    <li><%= link_to "Sign In", new_session_url %></li>
    <li><%= link_to "Sign Up", new_user_url %></li>
    <% end %>
    <li><%= link_to "About", about_url %></li>
    <li><%= link_to "Contact", contact_url %></li>
  </ul>
  <a href="#" class="nav-dropdown"><i class="fa fa-bars" aria-hidden="true"></i></a>
</nav>

<div class="tagline">
  <h3>Do stuff that makes a difference</h3>
</div>

app/views/shared/_sub_nav.html.erb
<div class="options">
  <a href="<%= suggestions_url %>" class="main-options main-selected">Actions</a>
  <a href="<%= events_url %>" class="main-options">Events</a>

  <a href="#" class="sub-options sub-selected">Hot</a>
  <a href="#" class="sub-options">Trending</a>
  <a href="#" class="sub-options">Near Me</a>
  <a href="#" class="sub-options">Category</a>
  <input type="text" name="" value="" placeholder="Search...">
</div>

<% if logged_in? %>
  <h4 class="create-options"><i class="fa fa-plus-circle" aria-hidden="true"></i> <%= link_to "Create Action", new_suggestion_url  %></h4>
  <h4 class="create-options"><i class="fa fa-plus-circle" aria-hidden="true"></i> <%= link_to "Create Event", new_event_url %></h4>
<% else %>
  <h4><%= link_to "Sign up", new_user_url %> or <%= link_to "Sign In", new_session_url %> to create an action or event.</h4>
<% end %>