config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#root'

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:create, :update, :show]
    get '/profile', to: 'users#profile'
    resource :session, only: [:create, :destroy]

    resources :categories, only: [:index, :create]
    resources :comments, only: [:create, :destroy]

    resources :suggestions, except: [:new, :edit] do
      patch "/pending_upvote", to: "suggestions#pending_upvote", as: "pending_upvote"
      patch "/ignore_upvote", to: "suggestions#ignore_upvote", as: "ignore_upvote"
      patch "/complete_upvote", to: "suggestions#complete_upvote", as: "complete_upvote"
    end

    resources :events, except: [:new, :edit] do
      patch "/pending_upvote", to: "events#pending_upvote", as: "pending_upvote"
      patch "/ignore_upvote", to: "events#ignore_upvote", as: "ignore_upvote"
      patch "/complete_upvote", to: "events#complete_upvote", as: "complete_upvote"
    end

    resources :contacts, only: [:create, :index]

    # get "/about", to: "static_pages#about", as: "about"
    # get "/contact", to: "contacts#new", as: "contact"
    #
    # get '/near_me', to: "events#near_me", as: "events_near_me"
    # get 'hot_events', to: "events#most_upvoted", as: "events_most_upvoted"
    # get 'trending_events', to: "events#trending", as: "events_trending"
    #
    # get 'hot_suggestions', to: "suggestions#most_upvoted", as: "suggestions_most_upvoted"
    # get 'trending_suggestions', to: "suggestions#trending", as: "suggestions_trending"
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

  has_many :idea_categories, dependent: :destroy, inverse_of: :category
  has_many :suggestions, through: :idea_categories, source: :idea, source_type: "Suggestion"
  has_many :events, through: :idea_categories, source: :idea, source_type: "Event"

  def events_by_creation
    events.order("created_at DESC")
  end

  def suggestions_by_creation
    suggestions.order("created_at DESC")
  end
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController
  def index
    @categories = Category.all
    render :index
  end
end

app/views/categories/_ideas.html.erb
<% message = idea_type == :event ? "events" : "actions" %>
<% action_url = idea_type == :event ? new_event_url : new_suggestion_url %>

<% if ideas.empty? %>
  <p>No <%= message %> are created yet in this category. Why don't you <%= link_to "create one", action_url %>?</p>
<% else %>
  <%= render partial: "layouts/short_idea", locals: { ideas: ideas, idea_type: idea_type } %>
<% end %>

app/views/categories/index.html.erb
<h1>Browse by Category</h1>
<% if admin? %>
  <%= link_to "Add Category", new_category_url %>
<% end %>

<ul>
  <% @categories.each do |category| %>
    <li><h4><%= link_to category.name, category_url(category) %></h4></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<form class="form-horizontal" action="<%= categories_url %>" method="post">
  <fieldset>
    <%= form_auth_token %>
    <legend>Add Category</legend>

    <div class="form-group">
      <label for="category_name" class="col-lg-2 control-label">Category Name</label>
      <div class="col-lg-10">
        <input id="category_name" type="text" name="category.name" class="form-control" value="<%= @category.name %>" placeholder="name">
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-info">Add Category</button>
      </div>
    </div>
  </fieldset>
</form>

app/views/categories/show.html.erb
<!-- STILL N + 1 QUERY HERE! -->

<h1><%= @category.name %></h1>

<a><%= link_to "Back to All Categories", categories_url %></a>
<br>
<a href="#events">Down to Events</a>

<h2>Actions</h3>
<%= render "ideas", idea_type: :suggestion, category: @category, ideas: @suggestions %>

<h2 id="events">Events</h2>
<p id="events"></p>
<%= render "ideas", idea_type: :event, category: @category, ideas: @events %>