config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#root'

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:create, :update, :show]
    get '/profile', to: 'users#profile'
    resource :session, only: [:create, :destroy]

    resources :categories, only: [:index, :create]
    resources :comments, only: [:create, :destroy]

    resources :suggestions, except: [:new, :edit] do
      patch "/pending_upvote", to: "suggestions#pending_upvote", as: "pending_upvote"
      patch "/ignore_upvote", to: "suggestions#ignore_upvote", as: "ignore_upvote"
      patch "/complete_upvote", to: "suggestions#complete_upvote", as: "complete_upvote"
    end

    resources :events, except: [:new, :edit] do
      patch "/pending_upvote", to: "events#pending_upvote", as: "pending_upvote"
      patch "/ignore_upvote", to: "events#ignore_upvote", as: "ignore_upvote"
      patch "/complete_upvote", to: "events#complete_upvote", as: "complete_upvote"
    end

    resources :contacts, only: [:create, :index]

    # get "/about", to: "static_pages#about", as: "about"
    # get "/contact", to: "contacts#new", as: "contact"
    #
    # get '/near_me', to: "events#near_me", as: "events_near_me"
    # get 'hot_events', to: "events#most_upvoted", as: "events_most_upvoted"
    # get 'trending_events', to: "events#trending", as: "events_trending"
    #
    # get 'hot_suggestions', to: "suggestions#most_upvoted", as: "suggestions_most_upvoted"
    # get 'trending_suggestions', to: "suggestions#trending", as: "suggestions_trending"
  end
end

app/views/layouts/_idea.html.erb
<% edit_url = idea_type == :event ? edit_event_url(idea) : edit_suggestion_url(idea) %>
<% delete_url = idea_type == :event ? event_url(idea) : suggestion_url(idea)%>
<% idea_string = idea_type == :event ? "Event" : "Action" %>

<div class="idea">
  <h1 class="idea-title"><%= idea.title  %></h1>
  <h3><%= categories_string(idea) %></h3>

  <h3 class="idea-info"><%= idea.upvotes_count %> activists</h3>
  <h3 class="idea-info">Created by: <%= idea.creator_name %></h3>
  <% if current_user == idea.creator %>
    <%= link_to "Edit #{idea_string}", edit_url, class: "button button-accept" %>
  <% end %>

  <% if current_user == idea.creator %>
    <%= button_to "Delete #{idea_string}", delete_url, method: :delete, class: "button button-accept" %>
  <% end %>

  <%= upvote_buttons(idea) %>

  <% if idea_type == :event %>
    <h3><%= idea.formatted_date %></h3>
    <% if idea.end_time %>
      <h3><%= idea.formatted_start_time %> to <%= idea.formatted_end_time %></h3>
    <% else %>
      <h3><%= idea.formatted_start_time %></h3>
    <% end %>

    <h3><%= idea.address %></h3>
    <h3><%= idea.city %>, <%= idea.state %></h3>
  <% end %>

  <p><%= idea.description %></p>

  <%= render partial: "comments/form",
  locals: { action_type: :new, idea: idea, comment: Comment.new } %>

  <p>All Comments</p>
  <% if idea.comments.empty? %>
    <p>None so far!</p>
    <% else %>
      <% idea.comments.order(:created_at).each do |comment| %>
        <h4><%= comment.author_name %> (<%= comment.time_string %>)</h4>
        <% if comment.user == current_user %>
          <%= button_to "Delete", comment_url(comment), method: :delete %>
        <% end %>
        <p><%= comment.body %></p>
      <% end %>
  <% end %>
</div>

app/views/layouts/_short_idea.html.erb
<% ideas.each do |idea| %>
  <% next if idea_type == :event && idea.in_past? %>
  <div class="short-idea">

    <h3 class="short-idea-header"><%= idea_link(idea) %> (<%= idea.upvotes_count %> activists)</h3>
    <div class="short-idea-body">
      <%= categories_string(idea) %>
      <%= idea.shortened_description %>
      <br>
      <%= location_info(idea) %>
      <%= time_info(idea) %>
      <%= upvote_buttons(idea) %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>F*** That Noise</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyB4O0OK1VwNaC1xyUiTDy9gYS3iNO3I3Ng" %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>